### ISSUE TITLE
I Need Help

### ISSUE THREAD

**Issue by leodxxx** [shashankvemuri/Finance#14]
Hi Shashankvemuri, I ran the code, and I get the following error. HTTPError: HTTP Error 403

I have entered the API that I generated in FMP.

I will be very grateful for your help.

![image](https://user-images.githubusercontent.com/109706766/190552836-af801f25-d9cb-4e3f-8dfe-edfae81e1b3b.png)

**Comment by Shokhecom** [comment]
fix it

**Comment by shashankvemuri** [comment]
It could be that your subscription plan to financial modeling prep does not include access to the cash flow statement data. Try replacing the API key in the following URL with your own key to see if you are getting an error message: https://financialmodelingprep.com/api/v3/cash-flow-statement/AAPL?period=quarter&limit=400&apikey=2a056baeb857d946b2d1157c3007aa3c.

**Comment by leodxxx** [comment]
Shashankvemuri, thank you! ok, is my subscrition plan
