### ISSUE TITLE
Module does not exist

### ISSUE THREAD

**Issue by Leiptr96** [shashankvemuri/Finance#28]
https://github.com/shashankvemuri/Finance/blob/7ad65a081036e0282d651c6e3e420b7cb32e2cd3/find_stocks/IBD_RS_Rating.py#L11
Hello friend 
There is no tickers module and if you mean ticker a new issue comes forward which is circular import can you please fix this.
Thank you for your contributions

**Comment by shashankvemuri** [comment]
Hello. The tickers module I am importing in the IBD_RS_Rating.py file is a local file in the parent directory of the Finance project.

If you just want to use IBD_RS_Rating.py as a standalone Python file, you can copy the copy the tickers_sp500() from tickers.py into IBD_RS_Rating.py and the program should work as intended.

Let me know if you have any further questions.
