### ISSUE TITLE
Considered adding options?

### ISSUE THREAD

**Issue by ApurvShah007** [shashankvemuri/Finance#6]
You have covered a lot of ground in computational finance but I would love to work with you and add some options trading scripts to this! @shashankvemuri

**Comment by shashankvemuri** [comment]
Thank you for reaching out! I'd love to do some options trading scripts but I am a bit busy nowadays. I will definitely reach out to you in the future to work together on those @ApurvShah007

**Comment by ApurvShah007** [comment]
Glad you replied.It is unfortunate that you cannot work on it now but do let me know when you have some time to spare. I have a lot of groundwork already laid down. I would to collaborate to add some machine-learning to those scripts and make them even better @shashankvemuri .

**Comment by shashankvemuri** [comment]
Sounds great, I'll reach out to you soon!

**Comment by ApurvShah007** [comment]
Great, looking forward to it! @shashankvemuri
